# Example usage of paw_ansible_role_nginx

# Simple include with default parameters
include paw_ansible_role_nginx

# Or with custom parameters:
# class { 'paw_ansible_role_nginx':
#   nginx_user => undef,
#   nginx_error_log => '/var/log/nginx/error.log warn',
#   nginx_pidfile => undef,
#   nginx_worker_processes => '"{{ ansible_processor_vcpus | default(ansible_processor_count) }}"',
#   nginx_extra_conf_options => undef,
#   nginx_worker_connections => '1024',
#   nginx_multi_accept => 'off',
#   nginx_mime_file_path => undef,
#   nginx_server_names_hash_bucket_size => '64',
#   nginx_client_max_body_size => '64m',
#   nginx_access_log => '/var/log/nginx/access.log main buffer=16k flush=2m',
#   nginx_sendfile => 'on',
#   nginx_tcp_nopush => 'on',
#   nginx_tcp_nodelay => 'on',
#   nginx_keepalive_timeout => '75',
#   nginx_keepalive_requests => '600',
#   nginx_server_tokens => 'on',
#   nginx_proxy_cache_path => undef,
#   server => undef,
#   nginx_conf_path => undef,
#   nginx_vhost_path => undef,
#   ansible_distribution_major_version => undef,
#   nginx_default_release => undef,
#   nginx_yum_repo_enabled => true,
#   nginx_zypper_repo_enabled => true,
#   nginx_ppa_use => false,
#   nginx_ppa_version => 'stable',
#   nginx_package_name => 'nginx',
#   nginx_service_state => 'started',
#   nginx_service_enabled => true,
#   nginx_conf_template => 'nginx.conf.j2',
#   nginx_vhost_template => 'vhost.j2',
#   nginx_extra_http_options => undef,
#   nginx_remove_default_vhost => false,
#   nginx_listen_ipv6 => true,
#   nginx_vhosts => [],
#   nginx_upstreams => [],
#   nginx_log_format => '\'$remote_addr - $remote_user [$time_local] "$request" \'\n\'$status $body_bytes_sent "$http_referer" \'\n\'"$http_user_agent" "$http_x_forwarded_for"\'',
# }
